language: php

php: [5.3, 5.4, 5.5, 5.6, hhvm]

notifications:
  email: false

before_script:
  - composer install --quiet --prefer-dist --no-interaction
  - phantomjs --version
  - phantomjs -w > /tmp/webdriver_output.txt &

script: ./bin/phpunit -v --coverage-text

after_script:
  - cat /tmp/webdriver_output.txt
